chromosomes: 1-22
data_dir: "data"
output_dir: "output/"
individuals: "{data_dir}/ids_list/cmr_british_ids.txt"
# phenotype_list: ["EpicardialFatVolume", "EFV_to_LVEDV_plus_RVEDV_ratio", "EFV_to_LVESV_plus_RVESV_ratio", "EFV_to_mean_LVV_plus_RVV_ratio", "EFV_to_totalLVEDV_plus_RVEDV_ratio", "EFV_to_total_LVESV_plus_RVESV_ratio", "EFV_to_mean_total_LVV_plus_RVV_ratio", "EpicardialFatVolume_adj", "EFV_to_LVEDV_plus_RVEDV_ratio_adj", "EFV_to_LVESV_plus_RVESV_ratio_adj", "EFV_to_mean_LVV_plus_RVV_ratio_adj", "EFV_to_LVEDV_plus_RVEDV_ratio_adj", "EFV_to_total_LVESV_plus_RVESV_ratio_adj", "EFV_to_mean_total_LVV_plus_RVV_ratio_adj"]
phenotype_list: ["EFV_to_total_LVEDV_plus_RVEDV_ratio"]
filename_patterns: {
  genotype: "code/yaml_files/genotype_patterns/genotype_patterns.yaml",
  phenotype: {
    phenotype_file: "cardiac_indices/EFT_adjusted.tsv",
    phenotype_file_tmp: "cardiac_indices/EFT_adjusted_tmp.tsv",
    covariates: ""
  },
  gwas: "GWAS__{{phenotype}}_GBR",
  covariates:
}
exec:
  plink: "plink"
