data_dirs:
  genotype: "../data/calls_filtered_31802"
  phenotype: "../data"
  individuals: "../data"
  output: "../output/all_individuals"
  tmp: "../data/tmp"
filename_pattern:
  phenotype_list: "run_params/phenotypes.txt"
  genotype: "ukb_cal_chr{chromosome}_v2_31802_indiv.bed"
  bim: "ukb_cal_chr{chromosome}_v2_31802_indiv.bim"
  fam: "ukb_cal_chr{chromosome}_v2_31802_indiv.fam"
  phenotype: "Cardiac_Adj_Function_Indexes_plus_covariates_11350.tsv"
  phenotype_tmp: "Cardiac_Adj_Function_Indexes_plus_covariates_11350_tmp.tsv"
  # individuals: "only_FID_IID.txt"
  gwas: "gwas__{phenotype}{suffix}"
  covariates: 
exec:
  sbat: "software_bgenie_sbat/sbat/executables/sbat_centos6.8_dynamic"
  plink: "plink"
chromosomes: 1-22
merge_chromosomes: True
