chromosomes: 1-22

sample_white_lists:
  - "data/ids_list/cmr_british_unrelated.txt"

sample_black_lists: 
  - "data/ids_list/EF_lt_50__old_segmentation.txt"

covariates: "config_files/covariates/std_covariates.yaml"

quality_control: "config_files/quality_control/quality_control.yaml"

filename_patterns: {
  # input
  genotype: "config_files/genotype_patterns/genotype_patterns.yaml",
  phenotype: "data/coma_output/{experiment}/latent_space.csv",
  phenotype_intermediate: "data/coma_output/{experiment}/{suffix}/latent_space.csv",
  tmpdir: "data/tmp/coma/{experiment}/{suffix}",
  # output
  gwas: "output/coma/{experiment}/{suffix}/GWAS__{{phenotype}}__{suffix}"
}

exec:
  plink: "plink"

# data_dir: "data"
# output_dir: "output/coma"
# experiment: "2020-09-11_02-13-41"

# suffix: "{covariates}__{sample_white_lists}__{quality_control}"
