chromosomes: 1-22

sample_white_lists:
  - "data/ids_list/cmr_british_unrelated.txt"

sample_black_lists: null

covariates_config: "config_files/covariates/std_covariates_PC.yaml"

quality_control: "config_files/quality_control/quality_control.yaml"

filename_patterns: {
  # input
  genotype: "config_files/genotype_patterns/genotype_patterns.yaml",
  phenotype: "data/coma_output/{experiment}/latent_space.csv",
  phenotype_intermediate: "data/coma_output/{experiment}/{suffix}/latent_space.csv",
  tmpdir: "data/tmp/coma/{experiment}/{suffix}",
  # output
  gwas: "output/coma/{experiment}/{suffix}/GWAS__{{phenotype}}__{suffix}"
}

exec:
  plink: "plink"

# suffix: "{covariates}__{sample_white_lists}__{quality_control}"
