chromosomes: 1-22

sample_white_lists:
  - "data/ids_list/cmr_british_ids.txt"
  - "data/ids_list/women.txt"

sample_black_lists: null

covariates: "config_files/covariates/std_covariates.yaml"

quality_control: "config_files/quality_control/quality_control.yaml"

filename_patterns: {
  # input
  genotype: "config_files/genotype_patterns/genotype_patterns.yaml",
  phenotype: "data/cardiac_indices/CMR_info_LVRVLARA_11350.csv",
  phenotype_intermediate: "data/cardiac_indices/adjusted_for_covariates/CMR_info_LVRVLARA_11350.csv",
  tmpdir: "data/tmp/traditional_indices/{suffix}",
  # output
  gwas: "output/traditional_indices/{suffix}/GWAS__{{phenotype}}__{suffix}"
}

exec:
  plink: "plink"

# suffix: "{covariates}__{sample_white_lists}__{quality_control}"