chromosomes: 1-22

sample_white_lists:
  - "data/ids_list/cmr_british_unrelated.txt"

sample_black_lists: null

covariates_config: "config_files/covariates/std_covariates_PC.yaml"

quality_control: "quality_control/quality_control.yaml"

filename_patterns: {
  # input
  genotype: "genotype_patterns/genotype_patterns.yaml",
  phenotype_file: "/home/home01/scrb/01_repos/CardiacCOMA/mlruns/{experiment_id}/{run_id}/artifacts/output/latent_vector.csv",
  phenotype_intermediate: "/home/home01/scrb/01_repos/CardiacCOMA/mlruns/{experiment_id}/{run_id}/artifacts/output/latent_vector_adj_10PCs.csv",
  # output
  gwas: "/home/home01/scrb/01_repos/CardiacCOMA/mlruns/{experiment_id}/{run_id}/artifacts/GWAS_adj_10PCs/GWAS__{{phenotype}}__{suffix}"
}

exec:
  plink: "plink"

# suffix: "{covariates}__{sample_white_lists}__{quality_control}"
