---
output:
  html_document: default
  pdf_document: default
---
```{r}
library(dplyr)
library(ggplot2)
library(glue)
```

### Load data
```{r}
data_dir <- "~/data/PhD/UKBB/cardiac_indices"
cardiac_old_df <- read.csv(glue("{data_dir}/Cardiac_Function_Indexes_11350.csv"))
cardiac_new_df <- read.csv(glue("{data_dir}/CMR_info_LVRVLARA_11350.csv"))

ef_df <- left_join(
  cardiac_new_df %>% select(ID, LVEF) %>% rename(LVEF_old=LVEF), 
  cardiac_old_df %>% select(ID, LVEF_automatic) %>% rename(LVEF_new=LVEF_automatic), 
  by="ID"
)
```

### Compare old with new EF values
```{r}
pp <- ggplot(ef_df, aes(x=LVEF_old, y=LVEF_new))
pp <- pp + geom_point(size=0.2)
pp <- pp + geom_density2d()
pp <- pp + geom_abline(slope = 1, intercept = 0)
pp
```

```{r}
hist(ef_df$LVEF_old)
```

```{r}
hist(ef_df$LVEF_new)
```

### Generate files of subject IDs with EF < 50%
```{r}
dir <- "~/data/PhD/UKBB/subject_ids"
output_file <- glue("{dir}/EF_lt_50__old_segmentation.txt")
cardiac_old_df %>% filter(LVEF_automatic < 50) %>% select(ID) %>% write.csv(file = output_file, quote = FALSE, row.names = FALSE)

output_file <- glue("{dir}/EF_lt_50__new_segmentation.txt")
cardiac_new_df %>% filter(LVEF < 50) %>% select(ID) %>% write.csv(file = output_file, quote = FALSE, row.names = FALSE)
```

```{r}

```