chromosomes: 1-22
data_dir: "data"
output_dir: "output/coma"
individuals: "individuals/gbr.yaml"
filename_patterns: {
  genotype: "genotype_patterns/genotype_patterns.yaml",
  phenotype: {
    phenotype_file: "coma_output/2020-09-30_13-05-47/latent_space_adjusted.csv",
    phenotype_file_tmp: "tmp/2020-09-30_13-05-47__latent_space.csv.tmp",
    covariates: ""
  },
  gwas: "GWAS__{{phenotype}}_GBR"
}
quality_control: "quality_control/quality_control.yaml"
# quality_control: "quality_control/no_quality_control.yaml"
exec:
  plink: "plink"